#! /bin/bash

gnuplot<<EOF
	set terminal postscript eps color solid linewidth 2 "Helvetica" 20
	set samples 500 #sample points
	set xrange [-0.5:0.5]
	set yrange [-0.3:1.3]
	Func_exact(x)=x<=0?1:0
	set output "res.eps"
	set multiplot layout 2,1 #multi plot
	plot 'res' using 1:2 pointtype 4 title "WENO",\
	     Func_exact(x) title "Exact"
	plot 'res' using 1:3 pointtype 4 title "Traditional",\
	     Func_exact(x) title "Exact"
	unset multiplot
EOF
